### ISSUE TITLE
Archive of Instagram causes Chrome to crash on replay 💥 

### ISSUE THREAD

**Issue by edsu** [webrecorder/archiveweb.page#194]
I created an archive of https://www.instagram.com/berniesanders/ while logged into Instagram, and not using autopilot. The page seemed to archive fine but when I went to replay it crashed Chrome!

You can find the WACZ file at https://edsu-webarchives.s3.amazonaws.com/tmp/bernie.wacz

It does seem to replay in ReplayWeb.Page though (Chrome & Firefox):

https://replayweb.page/?source=https%3A%2F%2Fedsu-webarchives.s3.amazonaws.com%2Ftmp%2Fbernie.wacz#view=pages

**Comment by rikifrank** [comment]
Hi, having the same issue when I'm archiving Facebok Reel
step to reproduce : goto https://www.facebook.com/reel/182489734945066
archive the page successful (extension v0.11.3), not using autopilot
click on 'browse archive' and then click on the latest archive to play, chrome crashed
I tried to download the wacz and replay it (https://replayweb.page/ -> choose file -> choose this wacz file from my computer)
and I got an error, attached screenshot 
![image (3)](https://github.com/webrecorder/archiveweb.page/assets/115136916/03925fcd-d641-442d-99c4-a83a583413e4)
chrome version 120.0.6099.109

**Comment by tsemachh** [comment]
[Uploading replayweb.page-1703597409385.log…]()
Attaching the console log when trying to replay on the replayweb page

**Comment by SB-JM** [comment]
Chrome still still crashes in attemp to replay Facebook, for example from this seed: https://www.facebook.com/hashtag/nordicwaste
Chrome: Version 124.0.6367.119 (Officiel version) (64-bit)

**Comment by edsu** [comment]
This page seems to crash Chrome when replaying in ArchiveWebPage (but not ReplayWebPage):

https://majles.alukah.net/showthread.php?t=184791

**Comment by ikreymer** [comment]
I think I've found the issue, and it appears to be something totally random! A particular header (that appears to be used by Facebook and Instagram) is causing the browser to crash when used in the extension.
The header is: 'origin-agent-cluster: ?0' and deals with origin isolation in the browser, not anything used by the page.

Will have a fix shortly which removes / prefixes this header as part of the usual header rewriting:

I've reported this issue here with a very simple repro:
https://issues.chromium.org/issues/351564775

**Comment by ikreymer** [comment]
Fixed in 0.12.4!

**Comment by philjoseph** [comment]
@ikreymer indeed there is no crash anymore but I am still unable to replay this post and still get this error:

<img width="363" alt="image" src="https://github.com/user-attachments/assets/52a01f15-fcf1-4c85-ad81-2ddfa36ee1a4">

Our goal is to succesfuly record reels, from Instagram, Facebook or Youtube
